export type MenuItem = { name: string; price: string; description?: string; tags?: string[] };
export type MenuCategory = { name: string; note?: string; items: MenuItem[] };

export const MENU_CATEGORIES: MenuCategory[] = [
  { name: "Appetizers", items: [
    { name: "Crispy Pork Chop", price: "12", description: "Marinated and fried Duroc pork chop · house salt & pepper" },
    { name: "Crab Croquette", price: "16", description: "3 pc gourmet crab cakes · boom boom sauce" },
    { name: "Sea Salt Edamame", price: "7", description: "Edamame · sea salt · black pepper", tags: ["V"] },
    { name: "Yuzu Parmesan Truffle Fries", price: "11", description: "Parmesan · truffle oil · furikake" },
    { name: "Hoisin Brussels Sprouts", price: "10", description: "Sweet chili hoisin · microgreens" },
    { name: "Honey Glazed Ribs", price: "16", description: "3 pc slow-braised pork ribs · yuzu slaw" },
    { name: "Wagyu Sando", price: "19", description: "Japanese milk bread · A5 wagyu · tare · miso butter onion" },
    { name: "Crab Rangoon", price: "9", description: "5 pc · cream cheese · imitation crab · sweet & sour" },
    { name: "Taiwanese Chicken Bites", price: "11", description: "Crispy chicken · Thai basil · house salt & pepper" },
    { name: "Boom Boom Shrimp", price: "16", description: "7 pc tiger shrimp · boom boom sauce", tags: ["Spicy"] },
  ]},
  { name: "Salads & Soups", items: [
    { name: "Hot & Sour Soup", price: "5", description: "Vegetable stock · bamboo shoot · wood ear · tofu · egg", tags: ["Spicy"] },
    { name: "Shiitake Miso Soup", price: "5", description: "Miso · shiitake · tofu · wakame · add crab +4" },
    { name: "Egg Drop Soup", price: "5", description: "Chicken stock · sweet corn · scallion · onion · egg" },
    { name: "Cucumber Salad", price: "6", description: "Garlic · red pepper · sweet and spicy marinade", tags: ["V", "Spicy"] },
    { name: "Seaweed Avocado Salad", price: "11", description: "Greens · avocado · yuzu onion dressing", tags: ["V"] },
    { name: "Prime Tenderloin Tataki", price: "19", description: "4 oz prime Angus tenderloin · yuzu ponzu · green salad" },
  ]},
  { name: "Soup Dumplings", note: "Six handcrafted pieces per order", items: [
    { name: "Berkshire Pork", price: "12" }, { name: "Chicken & Shiitake", price: "12" },
    { name: "Mala Pork", price: "15", tags: ["Spicy"] }, { name: "Crab & Pork", price: "16" },
    { name: "Truffle & Pork", price: "19" },
  ]},
  { name: "The Wok", note: "Served with rice", items: [
    { name: "Orange Chicken", price: "17", description: "Orange liqueur · orange peel oil · battered chicken · brown sauce" },
    { name: "General’s Chicken", price: "17", description: "Fried chicken thigh · General’s sauce" },
    { name: "Kung Pao Chicken", price: "17", description: "Zucchini · celery · peanut · water chestnut", tags: ["Spicy"] },
    { name: "Salt & Pepper Shrimp", price: "19", description: "Scallion · onion · red pepper · house spices" },
    { name: "Crispy Tofu", price: "15", description: "Scallion · onion · red pepper · house spices", tags: ["V"] },
    { name: "Black Pepper Steak", price: "27", description: "7 oz prime New York strip · black pepper sauce" },
    { name: "Crispy Fish Fillet", price: "18", description: "White fish · onion · red pepper · garlic · house salt & pepper" },
    { name: "Crab-Stuffed Salmon Teriyaki", price: "30", description: "Scottish salmon · blue crab · spicy mayo · seasonal vegetable" },
    { name: "Salmon Teriyaki", price: "19", description: "Scottish salmon · teriyaki · seasonal vegetable" },
    { name: "Golden Miso Black Cod", price: "24", description: "Miso-marinated black cod · seasonal vegetable" },
    { name: "Chimichurri Lamb Chops", price: "28", description: "3 pc · lemongrass aioli · seasonal vegetable · binchotan grilled" },
    { name: "Garlic String Beans", price: "16", description: "Fresh string beans · garlic · scallion · pork" },
    { name: "Broccoli Beef", price: "19", description: "Strip loin · broccoli · carrots · brown sauce" },
    { name: "Mongolian Beef", price: "19", description: "Strip loin · scallion · onion · chili pepper" },
    { name: "Basil Tofu", price: "15", description: "Basil · ginger · garlic · sweet soy glaze", tags: ["V"] },
    { name: "Garlic Bok Choy", price: "15", description: "Stir-fried bok choy · garlic", tags: ["V"] },
    { name: "Chicken Teriyaki", price: "18", description: "Brined chicken filet · teriyaki · Brussels sprouts" },
  ]},
  { name: "Noodles & Rice", items: [
    { name: "KM Fried Rice", price: "15–19", description: "White rice · egg · scallion · onion · choice of vegetable, chicken, beef, or shrimp" },
    { name: "Lo Mein", price: "15–19", description: "Napa · carrots · onion · choice of vegetable, chicken, beef, or shrimp" },
    { name: "Chili Wonton Noodles", price: "18", description: "White noodles · 4 wontons · house wonton sauce", tags: ["Spicy"] },
    { name: "Beef Noodle Soup", price: "18", description: "Handcrafted noodles · 72-hour beef broth · bok choy · braised beef shank" },
    { name: "Tonkotsu Ramen", price: "17", description: "10-hour pork broth · pork ribs · ramen egg · black garlic oil · spicy miso +1" },
  ]},
  { name: "Handmade Dumplings", items: [
    { name: "Berkshire Pork Buns", price: "11", description: "3 pc · Kurobuta pork · scallion · pan-fry +1" },
    { name: "Fried Pulled Pork Buns", price: "10", description: "3 pc · crispy bun · BBQ pulled pork" },
    { name: "Scallion Pancake", price: "7", description: "Flaky scallion pastry", tags: ["V"] },
    { name: "Chicken Teriyaki Buns", price: "11", description: "3 pc · pan-fried fluffy buns · onion · scallion" },
    { name: "Shrimp Shumai", price: "12", description: "5 pc · fresh shrimp · yuzu ponzu" },
    { name: "Dumpling Trio", price: "13", description: "Vegetable · pork & shrimp · chicken & vegetable" },
    { name: "Kimchi Wagyu Dumplings", price: "15", description: "5 pc pan-fried dumplings · wagyu · kimchi" },
    { name: "Szechuan Wontons", price: "12–14", description: "8 pc · spicy vinaigrette · pork, chicken, or vegetable", tags: ["Spicy"] },
    { name: "Soft-Shell Crab Bao", price: "16", description: "2 pc · yuzu slaw · boom boom sauce · basil oil" },
    { name: "Pork Belly Gua Bao", price: "15", description: "Soy-braised pork belly · cucumber · fried bun" },
  ]},
  { name: "Signature Rolls", items: [
    { name: "Bora Bora", price: "18", description: "Shrimp tempura · crab mix · seared scallops · miso butter · honey aioli" },
    { name: "Spring in Thailand", price: "18", description: "Shrimp tempura · smoked salmon · cream cheese · eel · sweet Thai chili" },
    { name: "Boujee Vibes", price: "29", description: "Prime steak · shrimp tempura · A5 wagyu · caviar · gold leaf" },
    { name: "Riptide", price: "20", description: "Kani · avocado · cucumber · baked snow crab · honey mayo" },
    { name: "Neptune’s Fury", price: "18", description: "Kani · yellowtail · cucumber · snow crab · tare" },
    { name: "Flaming Dragon", price: "18", description: "Kani · avocado · torched salmon · serrano · spicy mayo", tags: ["Spicy"] },
    { name: "Peach Tree", price: "16", description: "Shrimp tempura · cream cheese · avocado · tenkasu · honey mayo" },
    { name: "Peter’s Roll", price: "18", description: "Yellowtail · kani · Hokkaido scallop · serrano · tobiko · ponzu" },
    { name: "Midori Magic", price: "15", description: "Tofu skin · yamagobo · pickled radish · cucumber · avocado", tags: ["V"] },
    { name: "El Fuego", price: "18", description: "Kani · spicy tuna · serrano · tobiko · torched spicy aioli", tags: ["Spicy"] },
    { name: "Golden Tiger", price: "17", description: "Salmon · cream cheese · kani · cucumber · tempura fried" },
  ]},
  { name: "Classic Rolls", items: [
    { name: "California", price: "8", description: "Imitation crab · avocado · cucumber · arare" },
    { name: "Bagel", price: "10", description: "Smoked salmon · cream cheese · avocado · sesame" },
    { name: "Spicy Salmon", price: "10", description: "Spicy salmon · cucumber", tags: ["Spicy", "Raw"] },
    { name: "Shrimp Tempura", price: "10", description: "Shrimp tempura · avocado · cucumber" },
    { name: "Salmon Avocado", price: "10", description: "Scottish salmon · avocado · sesame", tags: ["Raw"] },
    { name: "Spicy Tuna", price: "10", description: "Spicy tuna · cucumber", tags: ["Spicy", "Raw"] },
    { name: "Fried Vegetable", price: "12", description: "Cucumber · cream cheese · avocado · yamagobo · eel sauce", tags: ["V"] },
    { name: "Traditional Maki", price: "8", description: "Tuna, yellowtail scallion, tuna belly scallion, salmon, cucumber, avocado, or sweet gourd" },
    { name: "Spicy California", price: "9", description: "Spicy kani · avocado · cucumber", tags: ["Spicy"] },
    { name: "Fried California", price: "13", description: "Tempura-fried imitation crab · cucumber · avocado" },
    { name: "Futomaki", price: "11", description: "Yamagobo · kanpyo · avocado · cucumber · inari" },
  ]},
  { name: "Sashimi & Nigiri", note: "Sashimi (3 pc) · Nigiri (2 pc)", items: [
    { name: "Akami · Bluefin Tuna", price: "13 / 8", tags: ["Raw"] }, { name: "Chu Toro · Medium Fatty Tuna", price: "18 / 14", tags: ["Raw"] },
    { name: "O-Toro · Extra Fatty Tuna", price: "21 / 16", tags: ["Raw"] }, { name: "Sake · Salmon", price: "10 / 7", tags: ["Raw"] },
    { name: "Hamachi · Yellowtail", price: "10 / 7", tags: ["Raw"] }, { name: "Anago · Sea Eel", price: "Nigiri 8" },
    { name: "Unagi · Freshwater Eel", price: "10 / 7" }, { name: "Kanpachi · Amberjack", price: "10 / 7", tags: ["Raw"] },
    { name: "Ikura · Salmon Roe", price: "11 / 8", tags: ["Raw"] }, { name: "Tako · Octopus", price: "10 / 7" },
    { name: "Ika · Squid", price: "9 / 6", tags: ["Raw"] }, { name: "Hotate · Scallop", price: "10 / 7", tags: ["Raw"] },
    { name: "Uni · Sea Urchin", price: "Market", tags: ["Raw"] }, { name: "A5 Wagyu", price: "Nigiri 13" },
    { name: "Amaebi · Sweet Shrimp", price: "Nigiri 13", tags: ["Raw"] }, { name: "Temaki Handroll Set", price: "29", description: "Spicy tuna · hamachi scallion · shrimp tempura · BBQ eel · A5 wagyu" },
  ]},
  { name: "Fresh Catch", items: [
    { name: "Yuzu Garlic Kanpachi", price: "17", description: "Amberjack · avocado · yuzu garlic · honey mayo", tags: ["Raw"] },
    { name: "Ahi Poke", price: "14", description: "Avocado · tuna · soy marinade · masago", tags: ["Raw"] },
    { name: "Bluefin Tuna Sampler", price: "20", description: "Akami · chu-toro · o-toro", tags: ["Raw"] },
    { name: "Truffle Chu-Toro", price: "19", description: "Truffle soy · kizami wasabi · sturgeon caviar", tags: ["Raw"] },
    { name: "Sashimi Tasting", price: "36", description: "11 pc · five kinds · chef’s selection", tags: ["Raw"] },
    { name: "Strawberry Hamachi Crudo", price: "15", description: "Strawberry vinaigrette · sea salt · basil oil · yuzu", tags: ["Raw"] },
    { name: "Nigiri Tasting", price: "35", description: "8 pc chef’s selection · add uni +10 · add tuna roll +4", tags: ["Raw"] },
    { name: "Spicy Tuna Crispy Rice", price: "16", description: "Fried sushi rice · eel sauce · spicy mayo · crispy garlic", tags: ["Raw", "Spicy"] },
  ]},
  { name: "Desserts", items: [
    { name: "Chocolate XLB", price: "10" }, { name: "Crème Brûlée", price: "8" },
    { name: "Ice Cream", price: "7", description: "Two scoops · hojicha, vanilla, or chocolate" },
  ]},
];

export const DRINK_CATEGORIES: MenuCategory[] = [
  { name: "Zero Proof", items: [
    { name: "Fountain Drinks", price: "3", description: "Coke · Diet Coke · Sprite · lemonade · ginger ale · orange Fanta · refillable" },
    { name: "Sweet or Unsweet Tea", price: "3", description: "Refillable" },
    { name: "Hot Tea", price: "5", description: "Oolong · jasmine · black" },
    { name: "Ramune", price: "4", description: "Original or strawberry" },
    { name: "Taiwanese Soda", price: "4.5", description: "Honey wintermelon · apple sidra · Taiwanese root beer" },
    { name: "Saratoga Water", price: "7", description: "Sparkling or still" },
    { name: "Flavored Mojito", price: "9", description: "Mint · lime · strawberry, peach, mango, guava, classic, or lychee +1" },
    { name: "Ube Cream Matcha", price: "8", description: "Condensed milk · matcha · coconut water · ube cream cold foam" },
    { name: "Piña Colada", price: "8", description: "Coconut milk · pineapple · lime · grenadine" },
    { name: "Brazilian Limade", price: "8", description: "Condensed milk · lime · fresh mint" },
    { name: "Hibiscus Mai Tai", price: "8", description: "Hibiscus tea · honey · orange · pineapple · lime" },
  ]},
  { name: "Craft Cocktails", items: [
    { name: "Soufflé Espresso Martini", price: "16", description: "Haku vodka · vanilla · Kahlúa · espresso · espresso foam" },
    { name: "Guava Lychee Gin & Tonic", price: "14", description: "Empress gin · guava nectar · lychee · tonic" },
    { name: "Cranberry Orange Mule", price: "15", description: "Tito’s · orange bitters · ginger beer · cranberry" },
    { name: "Oolong Whisperer", price: "15", description: "Hendrick’s · house oolong syrup · lemon · soda" },
    { name: "Dark Harvest", price: "16", description: "Asian dark rum · bramble berry reduction · sweet vermouth" },
    { name: "Crimson Bloom", price: "16", description: "Serrano-infused tequila · Cointreau · watermelon · orange · lime" },
    { name: "Moonlit Hare", price: "15", description: "Vodka · lychee liqueur · dry vermouth · lychee · yuzu" },
    { name: "Lavender Lady", price: "14", description: "Hendrick’s · crème de violette · St-Germain · lemon · soda" },
    { name: "Yuzu Sake Mojito", price: "14", description: "Sake · yuzu · mint · lime · soda" },
    { name: "Midnight Stallion", price: "17", description: "1792 bourbon · Angostura · five-spice honey · sesame oil · smoked" },
    { name: "Velvet Dawn", price: "14", description: "Vodka · Aperol · pineapple · lemon · rose water · grenadine" },
    { name: "Banana Republic", price: "19", description: "Banana-infused Addictivo añejo · Angostura bitters" },
    { name: "General Chicken Beak", price: "14", description: "Espolòn tequila · Thai chili · General’s sauce · lime · egg white · chili oil" },
    { name: "Red Retriever", price: "15", description: "Dark rum · Campari · pineapple · lime · prosecco" },
    { name: "Strawberry Matcha Martini", price: "15", description: "Tito’s · strawberry jasmine foam · vanilla · matcha · condensed milk" },
  ]},
  { name: "Beer, Sake & Soju", items: [
    { name: "Stella Artois", price: "7.5", description: "Draft" }, { name: "Sapporo", price: "6 / 7.5", description: "Bottle / draft" },
    { name: "Modelo", price: "7.5", description: "Draft" }, { name: "Tropicalia", price: "7.5", description: "Draft" },
    { name: "Corona · Asahi · Heineken · Miller Lite", price: "6", description: "Bottle" }, { name: "Heineken 0.0", price: "6", description: "Nonalcoholic bottle" },
    { name: "House Sake", price: "8.5", description: "8 oz bottle" }, { name: "Kizakura Nigori", price: "16", description: "300 ml bottle" },
    { name: "Kizakura Hana Junmai Ginjo", price: "15", description: "300 ml bottle" }, { name: "Dassai Blue 50 Junmai Daiginjo", price: "20 / 55", description: "8 oz / 720 ml" },
    { name: "Daikoku Masa-Mune Junmai Ginjo", price: "25", description: "300 ml bottle" }, { name: "Kubota Junmai Daiginjo", price: "50", description: "750 ml bottle" },
    { name: "Hakkaisan Tokubetsu Honjozo", price: "17 / 45", description: "8 oz / 750 ml" }, { name: "Hakkaisan Yukimuro Snow Aged", price: "85", description: "750 ml bottle" },
    { name: "Katoukichibee Shouten Gold", price: "50", description: "750 ml bottle" }, { name: "Jinro Is Back Soju", price: "15", description: "Original · sugar free · strawberry · white grape" },
  ]},
  { name: "Red Wine", items: [
    { name: "Austin Hope Cabernet Sauvignon", price: "14 / 70", description: "Paso Robles · glass / bottle" }, { name: "Duckhorn Decoy Cabernet", price: "15 / 45", description: "California · glass / bottle" },
    { name: "Duckhorn Cabernet Sauvignon", price: "90", description: "Napa Valley · bottle" }, { name: "Caymus Cabernet Sauvignon", price: "150", description: "Napa Valley · 1 L bottle" },
    { name: "Duckhorn Decoy Pinot Noir", price: "14 / 38", description: "California · glass / bottle" }, { name: "Louis Jadot Pinot Noir", price: "16 / 48", description: "Burgundy · glass / bottle" },
    { name: "Rebellious Red Blend", price: "11 / 33", description: "California · glass / bottle" }, { name: "Hahn Merlot", price: "10 / 30", description: "Central Coast · glass / bottle" },
    { name: "Duckhorn Merlot", price: "80", description: "Napa Valley · bottle" }, { name: "Michele Chiarlo Le Orme Barbera", price: "14 / 42", description: "Piedmont · glass / bottle" },
    { name: "Luigi Bosca Malbec", price: "14 / 42", description: "Mendoza · glass / bottle" }, { name: "Château Saint André Corbin", price: "55", description: "Bordeaux · bottle" },
  ]},
  { name: "White & Sparkling", items: [
    { name: "Pine Ridge Sauvignon Blanc", price: "11 / 33", description: "Napa Valley · glass / bottle" }, { name: "Duckhorn Sauvignon Blanc", price: "15 / 45", description: "North Coast · glass / bottle" },
    { name: "Frenzy Sauvignon Blanc", price: "36", description: "Marlborough · bottle" }, { name: "Kung Fu Girl Riesling", price: "10 / 30", description: "Columbia Valley · glass / bottle" },
    { name: "Shades of Blue Riesling", price: "11 / 33", description: "Mosel · glass / bottle" }, { name: "Louis Jadot Chardonnay", price: "13 / 39", description: "Burgundy · glass / bottle" },
    { name: "Daou Chardonnay", price: "15 / 45", description: "Paso Robles · glass / bottle" }, { name: "Pighin Pinot Grigio", price: "12 / 36", description: "Venezia Giulia · glass / bottle" },
    { name: "Mezzacorona Moscato", price: "11 / 33", description: "Alto Adige · glass / bottle" }, { name: "Ruffino Prosecco", price: "10 / 30", description: "Veneto · glass / bottle" },
    { name: "Tutto Mio Sweet Red", price: "9 / 25", description: "Puglia · glass / bottle" },
  ]},
  { name: "Whiskey", note: "Two-ounce pours · make any pour a cocktail +3", items: [
    { name: "Glenlivet 12 / 15", price: "12 / 21" }, { name: "Macallan 12 / 15 / 18", price: "20 / 40 / 80" },
    { name: "Balvenie 12", price: "16" }, { name: "Johnnie Walker Black / Blue", price: "13 / 70" },
    { name: "Suntory Hibiki / Toki", price: "22 / 11" }, { name: "Akashi Single Malt", price: "10" },
    { name: "Mars Shinshu Iwai 45", price: "9" }, { name: "Nikka Coffey Grain", price: "16" },
    { name: "Four Roses / 1792 Bourbon", price: "11 / 12" }, { name: "Elijah Craig / Woodford Reserve", price: "12 / 13" },
    { name: "Angel’s Envy Bourbon", price: "15" }, { name: "Eagle Rare 10 Year", price: "16" },
    { name: "Bulleit Rye / Angel’s Envy Rye", price: "10 / 20" }, { name: "Rémy Martin XO", price: "60" },
    { name: "Jameson 12 Year", price: "9" }, { name: "Kavalan Select", price: "16" },
  ]},
  { name: "Spirits", note: "Two-ounce pours · make any pour a cocktail +3", items: [
    { name: "Tanqueray", price: "13" }, { name: "Hendrick’s", price: "14" }, { name: "Another Gin by Hendrick’s", price: "15" }, { name: "Monkey 47", price: "16" },
    { name: "Bacardi", price: "8" }, { name: "Tanduay Dark Rum", price: "10" }, { name: "Ketel One", price: "8" }, { name: "Tito’s Vodka", price: "9" }, { name: "Haku", price: "10" }, { name: "Grey Goose", price: "12" },
    { name: "Dulce Vida Blanco", price: "8" }, { name: "Espolòn Blanco / Lalo", price: "11" }, { name: "Don Julio Blanco", price: "12" },
    { name: "Mi Campo Reposado", price: "11" }, { name: "Corralejo Reposado", price: "15" }, { name: "Addictivo Añejo", price: "19" },
    { name: "Teremana Añejo", price: "17" }, { name: "Don Julio 1942 Añejo", price: "48" }, { name: "Clase Azul Reposado", price: "35" },
    { name: "Clase Azul Gold", price: "70" }, { name: "Conejos Joven Oaxaca Mezcal", price: "13" },
  ]},
];

